#!/bin/bash
# $0 - Script path
# $1 - Package path
# $2 - Target location
# $3 - Target volume`

# mv /Applications/TypeNovel.App /Applications/TypeNovel.App.tmp
if [[ -e $2 ]]; then
    mv $2 $2.tmp
fi
